CREATE TABLE billing_audit_raw_line (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL DEFAULT 'ALIYUN',
    source_api VARCHAR(64) NOT NULL,
    source_billing_cycle VARCHAR(16) NULL,
    bill_date DATE NOT NULL,
    line_hash CHAR(64) NOT NULL,
    bill_account_id BIGINT NULL,
    bill_owner_id BIGINT NULL,
    payer_account_id BIGINT NULL,
    product_code VARCHAR(128) NULL,
    product_name VARCHAR(256) NULL,
    product_detail_code VARCHAR(128) NULL,
    product_detail VARCHAR(512) NULL,
    commodity_code VARCHAR(128) NULL,
    commodity_name VARCHAR(256) NULL,
    billing_item_code VARCHAR(128) NULL,
    billing_item VARCHAR(256) NULL,
    billing_type VARCHAR(128) NULL,
    subscription_type VARCHAR(64) NULL,
    instance_id VARCHAR(256) NULL,
    instance_name VARCHAR(512) NULL,
    region VARCHAR(128) NULL,
    zone VARCHAR(128) NULL,
    resource_group VARCHAR(256) NULL,
    cost_unit VARCHAR(256) NULL,
    usage_amount DECIMAL(24, 8) NULL,
    usage_unit VARCHAR(64) NULL,
    pretax_gross_amount DECIMAL(18, 6) NULL,
    invoice_discount DECIMAL(18, 6) NULL,
    deductible_amount DECIMAL(18, 6) NULL,
    pretax_amount DECIMAL(18, 6) NULL,
    cash_amount DECIMAL(18, 6) NULL,
    payment_amount DECIMAL(18, 6) NULL,
    outstanding_amount DECIMAL(18, 6) NULL,
    currency VARCHAR(16) NULL,
    tags TEXT NULL,
    raw_payload JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_billing_audit_raw_line_run_hash (run_id, line_hash),
    KEY idx_billing_audit_raw_line_run (run_id),
    KEY idx_billing_audit_raw_line_bill_date (bill_date),
    KEY idx_billing_audit_raw_line_product_code (product_code),
    KEY idx_billing_audit_raw_line_billing_item_code (billing_item_code),
    KEY idx_billing_audit_raw_line_instance (instance_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
